### ISSUE TITLE
Library import order

### ISSUE THREAD

**Issue by jakirkham** [gmarkall/nbep-7#12]
Raising to check whether this proposal will depend on library import order. IOW is this...

```python
import rmm
import numba.cuda
```

...different from this?

```python
import numba.cuda
import rmm
```

**Comment by gmarkall** [comment]
Assuming that `import rmm` is importing a version of RMM that tries to set the Numba memory manager on import, it is not - Numba does not initialize CUDA until the first CUDA operation.

In the first case, RMM would have imported `numba.cuda`, and set the memory manager, but not caused it to initialize CUDA.

In the second case, Numba will still accept the memory manager being set because no CUDA operations have yet been performed by the time `import rmm` runs and sets the memory manager.

**Comment by jakirkham** [comment]
That's a good point. So if a 3rd party library left it to the user to explicitly enable NBEP 7 style allocations, the import order shouldn't matter. Is that right?

**Comment by gmarkall** [comment]
That is correct - the import order won't matter, so you could do either of:

```python
from numba import cuda
import rmm

rmm.use_rmm_for_numba()
```

or

```python
import rmm
from numba import cuda


rmm.use_rmm_for_numba()
```

and have the same behaviour.

**Comment by leofang** [comment]
Thank you @gmarkall for confirmation. The import order is always a pita and hard to debug...

**Comment by gmarkall** [comment]
Thanks for raising the issue originally - I'll update the NBEP to make an explicit statement about the import order not affecting anything.

**Comment by gmarkall** [comment]
Closing this issue as I'm just editing the document to incorporate the details from this issue.
